// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtUFccygaVXxOoMjiFYwlTL3ZlfjYF4DA',
    appId: '1:778201268218:web:81355bcd1fa3b4ca8a6e43',
    messagingSenderId: '778201268218',
    projectId: 'lofi-app-123',
    authDomain: 'lofi-app-123.firebaseapp.com',
    storageBucket: 'lofi-app-123.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGkx1SkY_ZbedJ2jW7q4Xq9vgFj3_4-Xc',
    appId: '1:778201268218:android:9e710e297e43448f8a6e43',
    messagingSenderId: '778201268218',
    projectId: 'lofi-app-123',
    storageBucket: 'lofi-app-123.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTlWivodQpaqP0586NsL6gT7sIs6GkrBA',
    appId: '1:778201268218:ios:a073df295d7621de8a6e43',
    messagingSenderId: '778201268218',
    projectId: 'lofi-app-123',
    storageBucket: 'lofi-app-123.appspot.com',
    iosBundleId: 'com.example.lofiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTlWivodQpaqP0586NsL6gT7sIs6GkrBA',
    appId: '1:778201268218:ios:045375d60e35fff38a6e43',
    messagingSenderId: '778201268218',
    projectId: 'lofi-app-123',
    storageBucket: 'lofi-app-123.appspot.com',
    iosBundleId: 'com.example.lofiApp.RunnerTests',
  );
}
